import type { ActivityType, PaginatedResult, Product } from "./types";

export const activityTypes: ActivityType[] = [
  {
    id: "avaliacoes-sondagens-relatorios",
    name: "Avaliações, sondagens e relatórios",
    slug: "avaliacoes-sondagens-relatorios",
    description: "Materiais para diagnóstico, acompanhamento e registro.",
    sortOrder: 1,
    active: true,
  },
  {
    id: "kits-sala-de-aula",
    name: "Kits sala de aula",
    slug: "kits-sala-de-aula",
    description: "Recursos completos para organizar a rotina.",
    sortOrder: 2,
    active: true,
  },
  {
    id: "decoracao-sala-volta-as-aulas",
    name: "Decoração de sala - Volta às aulas",
    slug: "decoracao-sala-volta-as-aulas",
    description: "Painéis e decorações para a primeira semana.",
    sortOrder: 3,
    active: true,
  },
  {
    id: "apostilas",
    name: "Apostilas",
    slug: "apostilas",
    description: "Sequências didáticas e cadernos organizados.",
    sortOrder: 4,
    active: true,
  },
  {
    id: "alfabetizacao",
    name: "Alfabetização",
    slug: "alfabetizacao",
    description: "Leitura, escrita e consciência fonológica.",
    sortOrder: 5,
    active: true,
  },
  {
    id: "datas-comemorativas",
    name: "Datas comemorativas",
    slug: "datas-comemorativas",
    description: "Atividades para festas, murais e lembranças.",
    sortOrder: 6,
    active: true,
  },
  {
    id: "saeb",
    name: "SAEB",
    slug: "saeb",
    description: "Materiais voltados para avaliação e preparação.",
    sortOrder: 7,
    active: true,
  },
  {
    id: "educacao-infantil",
    name: "Educação Infantil",
    slug: "educacao-infantil",
    description: "Propostas lúdicas e pedagógicas para os pequenos.",
    sortOrder: 8,
    active: true,
  },
  {
    id: "kits-combos",
    name: "Kits/Combos",
    slug: "kits-combos",
    description: "Combos com melhor custo-benefício.",
    sortOrder: 9,
    active: true,
  },
  {
    id: "terceiro-ao-quinto-ano",
    name: "3º ao 5º ano",
    slug: "terceiro-ao-quinto-ano",
    description: "Atividades alinhadas aos anos finais do fundamental.",
    sortOrder: 10,
    active: true,
  },
  {
    id: "leitura-escrita",
    name: "Leitura-Escrita",
    slug: "leitura-escrita",
    description: "Produções focadas em leitura e escrita.",
    sortOrder: 11,
    active: true,
  },
  {
    id: "matematica",
    name: "Matemática",
    slug: "matematica",
    description: "Recursos para contagem, operações e raciocínio.",
    sortOrder: 12,
    active: true,
  },
  {
    id: "recursos-na-lata",
    name: "Recursos na lata",
    slug: "recursos-na-lata",
    description: "Atividades práticas para usar sem complicação.",
    sortOrder: 13,
    active: true,
  },
  {
    id: "sequencia-didatica",
    name: "Sequência didática",
    slug: "sequencia-didatica",
    description: "Projetos com começo, meio e fim bem organizados.",
    sortOrder: 14,
    active: true,
  },
  {
    id: "lembrancinhas",
    name: "Lembrancinhas",
    slug: "lembrancinhas",
    description: "Materiais delicados para datas especiais.",
    sortOrder: 15,
    active: true,
  },
  {
    id: "painel",
    name: "Painel",
    slug: "painel",
    description: "Painéis prontos para imprimir e montar.",
    sortOrder: 16,
    active: true,
  },
];

const now = new Date().toISOString();

export const seedProducts: Product[] = [
  {
    id: "kit-maio-laranja",
    slug: "kit-maio-laranja",
    title: "Kit Completo Maio Laranja com Plano de Aula",
    description: "Material pedagógico pronto para imprimir, montar e usar na sala de aula.",
    activityTypeSlug: "datas-comemorativas",
    priceCents: 1000,
    priceLabel: "R$ 10,00",
    pdfUrl: null,
    coverImageUrl: null,
    galleryUrls: [],
    featured: true,
    active: true,
    checkoutUrl: null,
    stripeProductId: null,
    stripePriceId: null,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "moldura-bambole",
    slug: "moldura-bambole-maio-laranja",
    title: "Moldura para Fotos no Bambolê – Maio Laranja",
    description: "Arquivo visual para montar exposição ou ação temática.",
    activityTypeSlug: "painel",
    priceCents: 600,
    priceLabel: "R$ 6,00",
    pdfUrl: null,
    coverImageUrl: null,
    galleryUrls: [],
    featured: false,
    active: true,
    checkoutUrl: null,
    stripeProductId: null,
    stripePriceId: null,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "alfabetizacao-base",
    slug: "alfabetizacao-base",
    title: "Sequência de Alfabetização",
    description: "Atividades de leitura e escrita em PDF para dias corridos.",
    activityTypeSlug: "alfabetizacao",
    priceCents: 1290,
    priceLabel: "R$ 12,90",
    pdfUrl: null,
    coverImageUrl: null,
    galleryUrls: [],
    featured: true,
    active: true,
    checkoutUrl: null,
    stripeProductId: null,
    stripePriceId: null,
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "rotina-escolar",
    slug: "planner-da-professora",
    title: "Planner da Professora",
    description: "Organização simples para rotina, planejamento e acompanhamento.",
    activityTypeSlug: "kits-sala-de-aula",
    priceCents: 1000,
    priceLabel: "R$ 10,00",
    pdfUrl: null,
    coverImageUrl: null,
    galleryUrls: [],
    featured: false,
    active: true,
    checkoutUrl: null,
    stripeProductId: null,
    stripePriceId: null,
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },
];

export function paginate<T>(items: T[], page: number, limit: number): PaginatedResult<T> {
  const safePage = Math.max(1, Number.isFinite(page) ? Math.floor(page) : 1);
  const safeLimit = Math.max(1, Math.min(100, Number.isFinite(limit) ? Math.floor(limit) : 12));
  const total = items.length;
  const totalPages = Math.max(1, Math.ceil(total / safeLimit));
  const start = (safePage - 1) * safeLimit;
  return {
    data: items.slice(start, start + safeLimit),
    pagination: {
      page: safePage,
      limit: safeLimit,
      total,
      totalPages,
    },
  };
}
